# USES electron-builder packages 
language: node_js
node_js:
  - '10'
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      cache:
        apt: true
        yarn: true
      addons:
        apt:
          packages:
              - libstdc++6
              - bsdtar
              - rpm
    - os: osx
      sudo: required
    - os: windows        
script:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then GH_TOKEN=<Prersonal Access Token> build -l --publish=always; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then GH_TOKEN=<Prersonal Access Token> build -w --publish=always; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then GH_TOKEN=<Prersonal Access Token> build -m --publish=always; fi
branches:
  only:
  - master
